version: '3.8'

services:
  web:
    build: .
    command: gunicorn viz_logs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=viz_logs.settings
      - MYSQL_DATABASE=vizlogs
      - MYSQL_USER=vizuser
      - MYSQL_PASSWORD=vizpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=vr_logs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

volumes:
  mysql_data: