# Generated by Django 4.2.25 on 2025-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VizData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_on_air', models.FloatField(blank=True, null=True)),
                ('time_on_camera', models.FloatField(blank=True, null=True)),
                ('viz_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('visibility_map', models.TextField(max_length=16383)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'viz_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
